packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@eslint/js": ^9.38.0
  "@expo/metro-runtime": ~55.0.6
  "@heroui/react": latest
  "@heroui/styles": latest
  "@hookform/resolvers": latest
  "@supabase/ssr": ^0.8.0
  "@supabase/supabase-js": ^2.94.1
  "@t3-oss/env-core": ^0.13.8
  "@t3-oss/env-nextjs": ^0.13.8
  "@tailwindcss/postcss": ^4.1.16
  "@tanstack/react-form": ^1.23.8
  "@tanstack/react-query": 5.90.8
  "@trpc/client": 11.10.0
  "@trpc/react-query": 11.10.0
  "@trpc/server": 11.10.0
  "@trpc/tanstack-react-query": 11.10.0
  "@types/node": 22.18.12
  class-variance-authority: ^0.7.1
  drizzle-orm: ^0.44.7
  drizzle-zod: ^0.8.3
  eslint: ^9.38.0
  expo-constants: ~55.0.8
  expo-linear-gradient: ~55.0.8
  expo-secure-store: ~55.0.8
  heroui-native: latest
  next: ^16.0.9
  postgres: ^3.4.8
  prettier: ^3.6.2
  react-hook-form: latest
  react-native: 0.83.2
  react-native-gesture-handler: ~2.30.0
  react-native-mmkv: latest
  react-native-reanimated: 4.2.1
  react-native-safe-area-context: ~5.6.2
  react-native-worklets: 0.7.4
  stripe: ^17.6.0
  superjson: 2.2.3
  tailwind-merge: ^3.4.0
  tailwind-variants: ^3.2.2
  tailwindcss: ^4.1.16
  typescript: ^5.9.3
  uniwind: latest
  utf-8-validate: ^5.0.2
  zod: ^4.1.12

catalogs:
  react19:
    "@types/react": ~19.2.0
    "@types/react-dom": ~19.2.0
    react: 19.2.0
    react-dom: 19.2.0

linkWorkspacePackages: true

nodeLinker: hoisted

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

overrides:
  "@types/minimatch": 5.1.2
  lightningcss: 1.30.1

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
  - expo-modules-core
